# Generated by Django 2.2.6 on 2019-10-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_textpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textpage',
            name='intro',
        ),
    ]
